version: '3'
services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - 5001:5001
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 5050:5050
        depends_on:
            - backend
            - frontend
