version: '3'
services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        volumes:
            - ./backend/db:/db
        ports:
            - 5000:5000
    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        ports:
            - 5001:5001
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - 5050:5050
        depends_on:
            - backend
            - frontend
